import { useCallback, useEffect, useRef, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Pause, Play, RotateCcw, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Heart, Clock3 } from 'lucide-react'
import { findTulipOnPath, tulips, messages } from '../data'
import { Tulip } from '../components/Tulip'
import { KawaiiCat } from '../components/KawaiiCat'

type Point = { x: number; y: number }
export function Game({ collected, onCollect, onReset, elapsed, onFinish, soundEffect }: { collected: number[]; onCollect: (id: number, msg?: number) => void; onReset: () => void; elapsed: number; onFinish: () => void; soundEffect: (kind: 'collect'|'reveal') => void }) {
  const [pos, setPos] = useState<Point>({ x: 50, y: 92 }); const [paused, setPaused] = useState(false); const [card, setCard] = useState<number | null>(null); const field = useRef<HTMLDivElement>(null); const previousPos = useRef(pos)
  const move = useCallback((dx: number, dy: number) => { if (paused || card !== null) return; setPos(p => ({ x: Math.max(4, Math.min(96, p.x + dx)), y: Math.max(7, Math.min(93, p.y + dy)) })) }, [paused, card])
  useEffect(() => { const down = (e: KeyboardEvent) => { const dirs: Record<string, Point> = { ArrowUp:{x:0,y:-4},w:{x:0,y:-4},W:{x:0,y:-4},ArrowDown:{x:0,y:4},s:{x:0,y:4},S:{x:0,y:4},ArrowLeft:{x:-4,y:0},a:{x:-4,y:0},A:{x:-4,y:0},ArrowRight:{x:4,y:0},d:{x:4,y:0},D:{x:4,y:0} }; if (dirs[e.key]) { e.preventDefault(); move(dirs[e.key].x, dirs[e.key].y) } }; window.addEventListener('keydown', down); return () => window.removeEventListener('keydown', down) }, [move])
  useEffect(() => { const found = findTulipOnPath(previousPos.current, pos, collected); previousPos.current = pos; if (found < 0) return; const total = collected.length + 1; const messageIndex = total % 3 === 0 ? total / 3 - 1 : undefined; onCollect(found, messageIndex); soundEffect(messageIndex === undefined ? 'collect' : 'reveal'); if (messageIndex !== undefined) queueMicrotask(() => setCard(messageIndex)) }, [pos, collected, onCollect, soundEffect])
  useEffect(() => { if (collected.length === 18 && card === null) onFinish() }, [collected.length, card, onFinish])
  const tapField = (e: React.PointerEvent) => { if (!field.current) return; const r = field.current.getBoundingClientRect(); setPos({ x: (e.clientX-r.left)/r.width*100, y: (e.clientY-r.top)/r.height*100 }) }
  return <main className="game-screen"><header className="game-hud glass"><div className="counter"><span>🌷</span><div><small>TULIPAS</small><strong>{collected.length}<i>/18</i></strong></div></div><div className="timer"><Clock3/><span>{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</span></div><div className="hud-actions"><button className="icon-button" onClick={() => setPaused(v=>!v)} aria-label={paused?'Continuar':'Pausar'}>{paused?<Play/>:<Pause/>}</button><button className="icon-button" onClick={onReset} aria-label="Reiniciar jogo"><RotateCcw/></button></div></header><section className="garden" ref={field} onPointerDown={tapField} aria-label="Jardim encantado. Clique para mover a personagem"><div className="path"/><span className="pond">◌</span><span className="bush b1">✿ ❀ ✿</span><span className="bush b2">❀ ✿</span>{tulips.map(([x,y],i)=><span key={i} className="tulip-pos" style={{left:`${x}%`,top:`${y}%`}}><Tulip collected={collected.includes(i)}/></span>)}<motion.div className="player" animate={{ left:`${pos.x}%`, top:`${pos.y}%` }} transition={{type:'spring',stiffness:250,damping:24}}><KawaiiCat small/></motion.div>{paused&&<div className="pause-overlay"><Play/><h2>Uma pausinha no jardim</h2><button className="primary" onClick={()=>setPaused(false)}>Continuar</button></div>}<div className="bonus"><Heart fill="currentColor"/></div></section><div className="mobile-pad" aria-label="Controles de movimento"><button onPointerDown={()=>move(0,-4)} aria-label="Mover para cima"><ArrowUp/></button><button onPointerDown={()=>move(-4,0)} aria-label="Mover para esquerda"><ArrowLeft/></button><button onPointerDown={()=>move(0,4)} aria-label="Mover para baixo"><ArrowDown/></button><button onPointerDown={()=>move(4,0)} aria-label="Mover para direita"><ArrowRight/></button></div><p className="game-tip">Aproxime-se das tulipas para colhê-las ✨</p><AnimatePresence>{card!==null&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.article className="message-card" initial={{scale:.7,rotate:-4}} animate={{scale:1,rotate:0}} exit={{scale:.7}} role="dialog" aria-modal="true"><span className="card-flower">🌷</span><p>RECADO DO JARDIM • {card+1}/6</p><h2>{messages[card]}</h2><button className="primary" autoFocus onClick={()=>setCard(null)}>Guardar no meu jardim</button></motion.article></motion.div>}</AnimatePresence></main>
}
